# Generated by Django 5.2 on 2025-06-03 18:02

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_guide_first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('tour_guide_last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('tour_guide_phone', models.CharField(max_length=20, verbose_name='טלפון נייד')),
                ('tour_guide_email', models.EmailField(max_length=254, verbose_name='כתובת מייל')),
                ('tour_guide_profile_picture', models.ImageField(blank=True, null=True, upload_to='guide_profiles/', verbose_name='תמונת פרופיל')),
                ('languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='שפות הדרכה')),
                ('specialties', models.CharField(blank=True, max_length=255, null=True, verbose_name='תחומי התמחות')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='ניסיון מקצועי')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='המלצות או קישורים')),
                ('facebook_link', models.URLField(blank=True, help_text='הזן קישור לעמוד הפייסבוק שלך', null=True, verbose_name='קישור לדף פייסבוק')),
                ('instagram_link', models.URLField(blank=True, help_text='הזן קישור לעמוד האינסטגרם שלך', null=True, verbose_name='קישור לדף אינסטגרם')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='קישור לוואטסאפ')),
                ('website_link', models.URLField(blank=True, null=True, verbose_name='אתר אינטרנט')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=255, verbose_name='כותרת ראשית')),
                ('tour_subtitle', models.CharField(db_column='כותרת_משנית', max_length=255, verbose_name='כותרת משנית')),
                ('tour_image', models.ImageField(db_column='תמונה ', upload_to='tours_images/', verbose_name='תמונה הראשית')),
                ('tour_date', models.DateField(db_column='תאריך', verbose_name='תאריך הסיור')),
                ('tour_description', models.CharField(blank=True, db_column='פרטי_הטיול', null=True, verbose_name='פרטי הטיול')),
                ('tour_start_time', models.TimeField(db_column='שעת_התחלה', verbose_name='שעת התחלה')),
                ('tour_end_time', models.TimeField(blank=True, null=True, verbose_name='שעת סיום משוערת')),
                ('meeting_point', models.CharField(db_column='מקום_המפגש', max_length=255, verbose_name='מקום מפגש')),
                ('google_maps_link', models.CharField(blank=True, db_column='קישור_למפות_גוגל', max_length=500, verbose_name='קישור לנקודת המפגש במפת גוגל')),
                ('tour_price', models.DecimalField(db_column='עלות', decimal_places=2, help_text='יש להזין את העלות בשקלים חדשים (₪)', max_digits=8, null=True, verbose_name='עלות הסיור')),
                ('target_audience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('משפחות', 'משפחות'), ('מבוגרים', 'מבוגרים'), ('מיטבי לכת', 'מיטבי לכת'), ('מיטיבי קשב', 'מיטיבי קשב')], db_column='קהל_יעד', help_text='ניתן לבחור יותר מאפשרות אחת על ידי לחיצה על Ctrl או Command', max_length=100, null=True, verbose_name='קהל יעד')),
                ('difficulty_level', models.CharField(blank=True, choices=[('קל', 'קל'), ('בינוני', 'בינוני'), ('קשה', 'קשה'), ('קשה מאוד', 'קשה מאוד')], db_column='רמת_קושי', max_length=20, null=True, verbose_name='רמת קושי')),
                ('required_equipment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('כובע', 'כובע'), ('מים', 'מים'), ('נעליים סגורות', 'נעליים סגורות'), ('קרם הגנה', 'קרם הגנה'), ('אחר', 'אחר')], db_column='ציוד_נדרש', help_text='ניתן לבחור יותר מפריט אחד על ידי לחיצה על Ctrl או Command', max_length=255, null=True, verbose_name='ציוד נדרש')),
                ('max_participants', models.PositiveIntegerField(db_column='מקסימום_משתתפים', default=30, verbose_name='מקסימום משתתפים')),
                ('tour_guide_name', models.ForeignKey(blank=True, db_column='שם_מדריך', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourguide', verbose_name='שם המדריך')),
            ],
        ),
        migrations.CreateModel(
            name='TravelerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_first_name', models.CharField(db_column='שם_פרטי', max_length=255)),
                ('traveler_last_name', models.CharField(db_column='שם_משפחה', max_length=255)),
                ('registration_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='קוד רישום')),
                ('traveler_phone', models.CharField(max_length=20)),
                ('traveler_email', models.EmailField(db_column='אימייל', max_length=254)),
                ('traveler_attendance', models.BooleanField(db_column='נוכחות', default=False)),
                ('tour', models.ForeignKey(db_column='סיור', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tours.tour')),
            ],
        ),
    ]
