# Generated by Django 5.2 on 2025-06-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_description',
        ),
    ]
