# Generated by Django 5.2 on 2025-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_difficulty_level_tour_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerregistration',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
